# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(356, 278)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.input_folder_button = QtWidgets.QPushButton(self.splitter)
        self.input_folder_button.setObjectName("input_folder_button")
        self.input_path_edit = QtWidgets.QLineEdit(self.splitter)
        self.input_path_edit.setObjectName("input_path_edit")
        self.output_folder_button = QtWidgets.QPushButton(self.splitter)
        self.output_folder_button.setObjectName("output_folder_button")
        self.output_path_edit = QtWidgets.QLineEdit(self.splitter)
        self.output_path_edit.setObjectName("output_path_edit")
        self.label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.required_width_edit = QtWidgets.QLineEdit(self.splitter)
        self.required_width_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.required_width_edit.setObjectName("required_width_edit")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.required_height_edit = QtWidgets.QLineEdit(self.splitter)
        self.required_height_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.required_height_edit.setObjectName("required_height_edit")
        self.start_button = QtWidgets.QPushButton(self.splitter)
        self.start_button.setObjectName("start_button")
        self.verticalLayout.addWidget(self.splitter)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Crop images"))
        self.input_folder_button.setText(_translate("MainWindow", "Input images folder"))
        self.output_folder_button.setText(_translate("MainWindow", "Output images folder"))
        self.label.setText(_translate("MainWindow", "Width, px"))
        self.label_2.setText(_translate("MainWindow", "Height, px"))
        self.start_button.setText(_translate("MainWindow", "Start"))
